[package]
name = "uki"
authors = ["smokingplaya"]
repository = "https://github.com/smokingplaya/uki"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
serde = {version = "1.0.210", features = ["derive"]}
serde_yml = "0.0.12"